export const ViewAllItems = [
    {
      id: 1,
      image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
      genre: 'Fiction',
      title: 'Book 1',
      copies: 5,
      author: 'Author 1',
      barcode: 123456789,
      language: 'English',
      year_of_prod: 2020,
      publisher: 'Publisher 1',
      subjects: 'Subject 1',
      price: 20,
      type: 'Hardcover',
      no_of_pages: 300,
      isbn: 'ISBN123',
      rack: 1,
      editor: 'Editor 1',
      edition_num: 1,
      quantity: 10,
    },
    {
      id: 2,
      image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
      genre: 'Non-Fiction',
      title: 'Book 2',
      copies: 3,
      author: 'Author 2',
      barcode: 987654321,
      language: 'English',
      year_of_prod: 2019,
      publisher: 'Publisher 2',
      subjects: 'Subject 2',
      price: 25,
      type: 'Paperback',
      no_of_pages: 250,
      isbn: 'ISBN456',
      rack: 2,
      editor: 'Editor 2',
      edition_num: 2,
      quantity: 5,
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
        genre: 'Non-Fiction',
        title: 'Book 2',
        copies: 3,
        author: 'Author 2',
        barcode: 987654321,
        language: 'English',
        year_of_prod: 2019,
        publisher: 'Publisher 2',
        subjects: 'Subject 2',
        price: 25,
        type: 'Paperback',
        no_of_pages: 250,
        isbn: 'ISBN456',
        rack: 2,
        editor: 'Editor 2',
        edition_num: 2,
        quantity: 5,
      },
      {
        id: 2,
        image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
        genre: 'Non-Fiction',
        title: 'Book 2',
        copies: 3,
        author: 'Author 2',
        barcode: 987654321,
        language: 'English',
        year_of_prod: 2019,
        publisher: 'Publisher 2',
        subjects: 'Subject 2',
        price: 25,
        type: 'Paperback',
        no_of_pages: 250,
        isbn: 'ISBN456',
        rack: 2,
        editor: 'Editor 2',
        edition_num: 2,
        quantity: 5,
      },
      {
        id: 2,
        image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
        genre: 'Non-Fiction',
        title: 'Book 2',
        copies: 3,
        author: 'Author 2',
        barcode: 987654321,
        language: 'English',
        year_of_prod: 2019,
        publisher: 'Publisher 2',
        subjects: 'Subject 2',
        price: 25,
        type: 'Paperback',
        no_of_pages: 250,
        isbn: 'ISBN456',
        rack: 2,
        editor: 'Editor 2',
        edition_num: 2,
        quantity: 5,
      },
      {
        id: 2,
        image: "https://m.media-amazon.com/images/I/81Zo5Ezez7L._AC_UF894,1000_QL80_.jpg",
        genre: 'Non-Fiction',
        title: 'Book 2',
        copies: 3,
        author: 'Author 2',
        barcode: 987654321,
        language: 'English',
        year_of_prod: 2019,
        publisher: 'Publisher 2',
        subjects: 'Subject 2',
        price: 25,
        type: 'Paperback',
        no_of_pages: 250,
        isbn: 'ISBN456',
        rack: 2,
        editor: 'Editor 2',
        edition_num: 2,
        quantity: 5,
      },

    
  ]