INSERT INTO `majors` (`name`) VALUES
('Computer Science'),
('Engineering'),
('Business Administration'),
('Psychology'),
('Biology'),
('Electrical Engineering'),
('Mechanical Engineering'),
('Civil Engineering'),
('Chemical Engineering'),
('Information Technology'),
('Finance'),
('Marketing'),
('Human Resource Management'),
('Economics'),
('English Literature');
