SELECT * FROM learnhub.users;

INSERT INTO users (username, password, fName, lName, UID, `type`, email, `active`)
VALUES 
('john_smith', 'password1', 'John', 'Smith', 'U1234567', 'student', 'john_smith@example.com', true),
('jane_doe', 'password2', 'Jane', 'Doe', 'U2345678', 'student', 'jane_doe@example.com', true),
('alice_johnson', 'password3', 'Alice', 'Johnson', 'U3456789', 'student', 'alice_johnson@example.com', true),
('robert_green', 'password4', 'Robert', 'Green', 'U4567890', 'student', 'robert_green@example.com', true),
('emily_brown', 'password5', 'Emily', 'Brown', 'U5678901', 'student', 'emily_brown@example.com', true),
('david_taylor', 'password6', 'David', 'Taylor', 'I123456', 'instructor', 'david_taylor@example.com', true),
('sarah_miller', 'password7', 'Sarah', 'Miller', 'I234567', 'instructor', 'sarah_miller@example.com', true),
('michael_wilson', 'password8', 'Michael', 'Wilson', 'I345678', 'instructor', 'michael_wilson@example.com', true),
('laura_anderson', 'password9', 'Laura', 'Anderson', 'I456789', 'instructor', 'laura_anderson@example.com', true),
('kevin_jones', 'password10', 'Kevin', 'Jones', 'A123456', 'admin', 'kevin_jones@example.com', true),
('amanda_clark', 'password11', 'Amanda', 'Clark', 'A234567', 'admin', 'amanda_clark@example.com', true),
('jason_white', 'password12', 'Jason', 'White', 'A345678', 'admin', 'jason_white@example.com', true),
('melissa_harris', 'password13', 'Melissa', 'Harris', 'A456789', 'admin', 'melissa_harris@example.com', true),
('alex_thomas', 'password14', 'Alex', 'Thomas', 'U6789012', 'student', 'alex_thomas@example.com', true),
('rebecca_wood', 'password15', 'Rebecca', 'Wood', 'U7890123', 'student', 'rebecca_wood@example.com', true),
('matthew_cook', 'password16', 'Matthew', 'Cook', 'U8901234', 'student', 'matthew_cook@example.com', true),
('samantha_evans', 'password17', 'Samantha', 'Evans', 'U9012345', 'student', 'samantha_evans@example.com', true),
('ryan_martin', 'password18', 'Ryan', 'Martin', 'I567890', 'instructor', 'ryan_martin@example.com', true),
('natalie_long', 'password19', 'Natalie', 'Long', 'I678901', 'instructor', 'natalie_long@example.com', true),
('justin_hill', 'password20', 'Justin', 'Hill', 'I789012', 'instructor', 'justin_hill@example.com', true),
('kimberly_adams', 'password21', 'Kimberly', 'Adams', 'I890123', 'instructor', 'kimberly_adams@example.com', true),
('brian_parker', 'password22', 'Brian', 'Parker', 'A567890', 'admin', 'brian_parker@example.com', true),
('jessica_carter', 'password23', 'Jessica', 'Carter', 'A678901', 'admin', 'jessica_carter@example.com', true),
('patrick_scott', 'password24', 'Patrick', 'Scott', 'A789012', 'admin', 'patrick_scott@example.com', true),
('stephanie_richards', 'password25', 'Stephanie', 'Richards', 'A890123', 'admin', 'stephanie_richards@example.com', true),
('daniel_walker', 'password26', 'Daniel', 'Walker', 'U90123456', 'student', 'daniel_walker@example.com', true),
('ashley_morris', 'password27', 'Ashley', 'Morris', 'U01234567', 'student', 'ashley_morris@example.com', true),
('chris_campbell', 'password28', 'Chris', 'Campbell', 'U12345678', 'student', 'chris_campbell@example.com', true),
('jennifer_lee', 'password29', 'Jennifer', 'Lee', 'U23456789', 'student', 'jennifer_lee@example.com', true),
('eric_king', 'password30', 'Eric', 'King', 'I901234', 'instructor', 'eric_king@example.com', true),
('linda_roberts', 'password31', 'Linda', 'Roberts', 'I012345', 'instructor', 'linda_roberts@example.com', true),
('peter_wright', 'password32', 'Peter', 'Wright', 'I1254569', 'instructor', 'peter_wright@example.com', true),
('kelly_scott', 'password33', 'Kelly', 'Scott', 'I254567', 'instructor', 'kelly_scott@example.com', true),
('jacob_hall', 'password34', 'Jacob', 'Hall', 'A901234', 'admin', 'jacob_hall@example.com', true),
('samantha_king', 'password35', 'Samantha', 'King', 'A012345', 'admin', 'samantha_king@example.com', true),
('nathan_young', 'password36', 'Nathan', 'Young', 'A1234567', 'admin', 'nathan_young@example.com', true),
('mary_cook', 'password37', 'Mary', 'Cook', 'A2345677', 'admin', 'mary_cook@example.com', true),
('joseph_mitchell', 'password38', 'Joseph', 'Mitchell', 'U3556789', 'student', 'joseph_mitchell@example.com', true),
('diana_martinez', 'password39', 'Diana', 'Martinez', 'U5567890', 'student', 'diana_martinez@example.com', true),
('tyler_ward', 'password40', 'Tyler', 'Ward', 'I335678', 'instructor', 'tyler_ward@example.com', true);


